version: 2.1
orbs:
  rust: circleci/rust@1.6.0
executors:
    circleci-base:
        docker:
            - image: cimg/base:2023.07
jobs:
    setup_environment:
        executor: circleci-base
        parameters:
            rust_version:
                type: string
            protobuf_version:
                type: string
        steps:
            - checkout
            - run:
                environment:
                    INSTALL_PREFIX: ~/.local
                    PROTOBUF_VERSION: << parameters.protobuf_version >>
                command: ./install_dependencies.sh
            - persist_to_workspace:
                root: ~/
                paths:
                    - .local
            - rust/install:
                version: << parameters.rust_version >>
            - persist_to_workspace:
                root: ~/
                paths:
                    - .cargo
    format-lint:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - rust/format:
                working_directory: << parameters.working_directory >>
            - rust/clippy:
                working_directory: << parameters.working_directory >>
    build:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - attach_workspace:
                at: ~/
            - rust/build:
                working_directory: << parameters.working_directory >>
    test:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - rust/test:
                working_directory: << parameters.working_directory >>

workflows:
    build:
        jobs:
            - setup_environment:
                name: setup_environment-protobuf_<< matrix.protobuf_version >>-rust_<< matrix.rust_version >>
                matrix:
                    parameters:
                        protobuf_version: ["3.0.0", "3.5.1", "3.6.1", "23.3"]
                        rust_version: ["1.70.0", "stable", "nightly"]
            - build:
                working_directory: "."
                requires:
                    - setup_environment
