version: 2.1
orbs:
  rust: circleci/rust@1.6.0
jobs:
    format-lint:
        docker: &docker_stable
            - image: cimg/rust:1.70
        steps:
            - checkout
            - rust/format
            - rust/clippy
    build-example:
        docker: *docker_stable
        steps:
            - checkout
            - rust/build:
                working_directory: example
    format-lint-example:
        docker: *docker_stable
        steps:
            - checkout
            - rust/format:
                working_directory: example
            - rust/clippy:
                working_directory: example
    build-test:
        parameters:
            rust-version:
                type: string
            protobuf-version:
                type: string
        docker:
            - image: cimg/rust:<< parameters.rust-version >>
        steps:
            - checkout
            - run:
                environment:
                    PROTOBUF_VERSION: << parameters.protobuf-version >>
                command: ./install_dependencies.sh
            - rust/test

workflows:
    default:
        jobs:
            - format-lint
            - build-example
            - format-lint-example:
                requires:
                    - build-example
            - build-test:
                requires:
                    - format-lint
                matrix:
                    parameters:
                        rust-version: ["1.70", "nightly"]
                        protobuf-version: ["3.0.0", "3.5.1", "3.6.1"]
