version: 2.1
orbs:
  rust: circleci/rust@1.6.0
executors:
    circleci-base:
        docker:
            - image: cimg/base:2023.07
jobs:
    checkout:
        executor: circleci-base
        steps:
            - checkout
    install-rust:
        executor: circleci-base
        parameters:
            rust_version:
                type: string
        steps:
            - rust/install:
                version: << parameters.rust_version >>
    install-protobuf:
        executor: circleci-base
        parameters:
            protobuf_version:
                type: string
        steps:
            - run:
                environment:
                    PROTOBUF_VERSION: << parameters.protobuf_version >>
                command: ./install_dependencies.sh
    format-lint:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - rust/format:
                working_directory: << parameters.working_directory >>
            - rust/clippy:
                working_directory: << parameters.working_directory >>
    build:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - rust/build:
                working_directory: << parameters.working_directory >>
    test:
        executor: circleci-base
        parameters:
            working_directory:
                type: string
        steps:
            - rust/test:
                working_directory: << parameters.working_directory >>

workflows:
    default:
        jobs:
            - install-rust:
                name: install-rust-<< matrix.rust_version >> 
                matrix:
                    parameters: &rust_versions
                        rust_version: ["1.70", "stable", "nightly"]
            - install-protobuf:
                name: install-protobuf-<< matrix.protobuf_version >>
                matrix:
                    parameters: &protobuf_versions
                        protobuf_version: ["3.0.0", "3.5.1", "3.6.1", "23.3"]
            - checkout
            - build:
                name: build-<< matrix.working_directory >>
                matrix:
                    parameters:
                        working_directory: [".", "example"]
